# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-11-10T17:09:18+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Request(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    queryString: str
    resultType: str
    cursorMark: str
    pageSize: int
    sort: str
    synonym: bool


class FullTextIdList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fullTextId: list[str]


class AuthorId(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: str
    value: str


class AuthorAffiliationItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    affiliation: str


class AuthorAffiliationDetailsList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    authorAffiliation: list[AuthorAffiliationItem]


class AuthorItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fullName: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    initials: str | None = None
    authorId: AuthorId | None = None
    authorAffiliationDetailsList: AuthorAffiliationDetailsList | None = None
    collectiveName: str | None = None


class AuthorList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    author: list[AuthorItem]


class AuthorIdItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: str
    value: str


class AuthorIdList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    authorId: list[AuthorIdItem]


class DataLinksTagsList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dataLinkstag: list[str]


class Journal(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    title: str
    medlineAbbreviation: str
    isoabbreviation: str
    nlmid: str
    issn: str
    essn: str


class JournalInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    issue: str | None = None
    volume: str | None = None
    journalIssueId: int
    dateOfPublication: str
    monthOfPublication: int
    yearOfPublication: int
    printPublicationDate: str
    journal: Journal


class PubTypeList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pubType: list[str]


class GrantItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    grantId: str | None = None
    agency: str
    acronym: str | None = None
    orderIn: int


class GrantsList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    grant: list[GrantItem]


class MeshQualifierItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    abbreviation: str
    qualifierName: str
    majorTopic_YN: str


class MeshQualifierList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    meshQualifier: list[MeshQualifierItem]


class MeshHeadingItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    majorTopic_YN: str
    descriptorName: str
    meshQualifierList: MeshQualifierList | None = None


class MeshHeadingList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    meshHeading: list[MeshHeadingItem]


class KeywordList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    keyword: list[str]


class ChemicalItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    name: str
    registryNumber: str


class ChemicalList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    chemical: list[ChemicalItem]


class SubsetItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    code: str
    name: str


class SubsetList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    subset: list[SubsetItem]


class FullTextUrlItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    availability: str
    availabilityCode: str
    documentStyle: str
    site: str
    url: str


class FullTextUrlList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fullTextUrl: list[FullTextUrlItem]


class CommentCorrectionItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str
    source: str
    reference: str | None = None
    type: str
    orderIn: int
    note: str | None = None


class CommentCorrectionList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    commentCorrection: list[CommentCorrectionItem]


class TmAccessionTypeList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    accessionType: list[str]


class InvestigatorItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fullName: str
    firstName: str
    lastName: str
    initials: str


class InvestigatorList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    investigator: list[InvestigatorItem]


class BookOrReportDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    publisher: str
    yearOfPublication: int


class VersionItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str
    source: str
    firstPublishDate: str
    versionNumber: int
    pubTypeList: PubTypeList
    hasEvaluations: str


class VersionList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    version: list[VersionItem]


class ResultItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str
    source: str
    pmid: str | None = None
    pmcid: str | None = None
    fullTextIdList: FullTextIdList | None = None
    doi: str | None = None
    title: str
    authorString: str | None = None
    authorList: AuthorList | None = None
    authorIdList: AuthorIdList | None = None
    dataLinksTagsList: DataLinksTagsList | None = None
    journalInfo: JournalInfo | None = None
    pubYear: str
    pageInfo: str | None = None
    abstractText: str | None = None
    affiliation: str | None = None
    publicationStatus: str | None = None
    language: str | None = None
    pubModel: str | None = None
    pubTypeList: PubTypeList
    grantsList: GrantsList | None = None
    meshHeadingList: MeshHeadingList | None = None
    keywordList: KeywordList | None = None
    chemicalList: ChemicalList | None = None
    subsetList: SubsetList | None = None
    fullTextUrlList: FullTextUrlList
    commentCorrectionList: CommentCorrectionList | None = None
    isOpenAccess: str
    inEPMC: str
    inPMC: str
    hasPDF: str
    hasBook: str
    hasSuppl: str
    citedByCount: int
    hasData: str
    hasReferences: str
    hasTextMinedTerms: str
    hasDbCrossReferences: str
    hasLabsLinks: str
    license: str | None = None
    hasEvaluations: str
    authMan: str
    epmcAuthMan: str
    nihAuthMan: str
    hasTMAccessionNumbers: str
    tmAccessionTypeList: TmAccessionTypeList | None = None
    dateOfCompletion: str | None = None
    dateOfCreation: str
    firstIndexDate: str
    fullTextReceivedDate: str | None = None
    dateOfRevision: str | None = None
    firstPublicationDate: str
    electronicPublicationDate: str | None = None
    investigatorList: InvestigatorList | None = None
    manuscriptId: str | None = None
    bookOrReportDetails: BookOrReportDetails | None = None
    versionList: VersionList | None = None
    versionNumber: int | None = None


class ResultList(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    result: list[ResultItem]


class Model(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    version: str
    hitCount: int
    nextCursorMark: str | None = None
    nextPageUrl: str | None = None
    request: Request
    resultList: ResultList
